.gitignore
.travis.yml
README.md
config/database.yml

* add travis ci status badge
* add link to example application

add travis ci status badge

---

Gemfile
Gemfile.lock
app/assets/stylesheets/simple_form-bootstrap/_form_floating_labels.scss

* update bootstrap to v4.1.3
* `bundle update bootstrap`

update bootstrap to v4.1.3

---

Gemfile
Gemfile.lock

* lock sqlite3 version
:link: https://github.com/rafaelfranca/simple_form-bootstrap/pull/98

lock sqlite3 version

---

Gemfile
Gemfile.lock
app/assets/stylesheets/simple_form-bootstrap/_form_collection_label.scss
config/initializers/simple_form_bootstrap.rb
test/simple_form-bootstrap/custom_fields_test.rb
test/simple_form-bootstrap/horizontal_form_test.rb
test/simple_form-bootstrap/vertical_form_test.rb

* add `item_label_class` for for radio buttons and check boxes collection
* 🔗 https://github.com/plataformatec/simple_form/pull/1637
* update vertical form
* update horizontal form
* update custom form
* update css comments
Kudos to ✨ @feliperenan ✨

add item_label_class for for radio buttons and check boxes collection

---

app/assets/stylesheets/simple_form-bootstrap/_form_floating_labels.scss
app/views/examples/floating_labels/_bootstrap.html.erb
config/initializers/simple_form_bootstrap.rb
test/simple_form-bootstrap/floating_labels_test.rb

* refine form with floating labels
* fix issues with `.custom-select`

refine form with floating labels

---

Gemfile
Gemfile.lock

* use simple_form `v5.0.0` via rubygems

use simple_form v5.0.0 via rubygems

---

.github/workflows/ci.yml
.github/workflows/ruby.yml

* add basic ruby / ci workflow with github actions
* run `rake test` similar to `.travis.yml`

add basic ruby github worklow

---

.github/workflows/ci.yml

* use actions/checkout `v2`
* https://github.com/actions/checkout

use actions/checkout v2

---

.github/workflows/ci.yml

* try to reset the action cache
* temp. rename cache key

try to reset the action cache

---

.github/workflows/ci.yml

* use ruby/setup-ruby action
* https://github.com/ruby/setup-ruby
* https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

use ruby/setup-ruby action

---

README.md
app/views/application/_footer.html.erb
app/views/application/_jumbotron.html.erb
app/views/documentation/index.html.erb
config/initializers/simple_form_bootstrap.rb

* update path from `plataformatec` to `heartcombo`
* see: http://blog.plataformatec.com.br/2020/01/important-information-about-our-elixir-and-ruby-open-source-projects/

update github path to simple_form

---

README.md

* sync license paragraph with `heartcombo/simple_form`
:link: https://github.com/heartcombo/simple_form/blob/master/README.md#license

Update license section

---

README.md

use generic Heroku url to be independent

use generic Heroku url

---

MIT-LICENSE
app/views/application/_footer.html.erb

* update application footer
* update License file

update license information

---

config/environments/production.rb

* remove custom uglifier config
* fix for failing heroku deployments 😥

remove custom uglifier config

---

app/assets/javascripts/toggle_controller.js

* prevent click handler from called a second time
* add `preventDefault()`

fix minor bug in toggle controller

---

app/javascript/controllers/toggle_controller.js

* only show toggle controlls on example pages

only show toggle controlls on example pages

---

Gemfile.lock

* update bootstrap v5.1.3
* run `bundle update bootstrap`

update bootstrap v5.1.3

---

Gemfile
Gemfile.lock
app/models/user.rb

* use Rails 7 comparison validations
* remove validates_timeliness gem
* :book: https://guides.rubyonrails.org/active_record_validations.html#comparison

use Rails 7 comparison validations

---

config/initializers/simple_form_bootstrap.rb

* Update SimpleForm bootstrap initializer banner
* remove a misleading sentence
* `Please do not make direct changes to this file!`
* :link: https://github.com/heartcombo/simple_form/issues/1756
/cc @carlosantoniodasilva @collimarco

Update sf bootstrap initializer banner
